pipeline.sh
pipeline_annotate.sh
pipeline_filter.sh
pipeline_preprocess.sh
pipeline_report.sh

Tested with:
```
sbatch --qos=priority --constraint=tmp01 --output=../outA/vip.out --error=../outA/vip.err pipeline.sh -i test/data/test.vcf -o ../outA/out.vcf
sbatch --qos=priority --constraint=tmp01 --output=outB/vip.out --error=outB/vip.err vip/pipeline.sh -i vip/test/data/test.vcf -o outB/out.vcf
sh vip/pipeline.sh -i vip/test/data/test.vcf -o outC/out.vcf
```

Fixes #40 for introduced sbatch issues

---

.github/pull_request_template.md

Based on [this one](https://github.com/molgenis/molgenis-app-vibe/blob/a2a9fdcebac56f88f0a726f5ad390eaa64b82f9b/.github/PULL_REQUEST_TEMPLATE.md) with an added step to test `sh test/pipeline_test.sh`. Adjusting this to better fit the repository might be of added benefit, but for now at least one will be present.

Added a basic pull request template

---

README.md
pipeline.sh
pipeline_filter.sh

Pipeline option to use custom decision tree

---

pipeline_annotate.sh
pipeline_filter.sh
pipeline_preprocess.sh
pipeline_report.sh
utils/header.sh

Fix #14 Fix module versions (backport)

---

utils/header.sh

- [N.A.] Documentation was updated
Does not continue checking remaining modules when first missing module is found.

Added #60 Check if all modules are available before running pipeline.

---

utils/header.sh

Fix #65 Use CADD/v1.4-foss-2018b-minimal when available

---

pipeline_1_annotate.sh

- [will test when v1.0.x is available] Functionality works & meets specs
- [will test when v1.0.x is available] No issues running `sh test/pipeline_test.sh`
- [N.A] Documentation was updated
None.

Fix #65 Fallback to CADD/v1.4-foss-2018b-minimal (backport)

---

pipeline_1_annotate.sh

- [will test when v1.0.x is available] Functionality works & meets specs
- [will test when v1.0.x is available] No issues running `sh test/pipeline_test.sh`
- [N.A] Documentation was updated
None.

Fix unload CADD module in case CADD/v1.4-foss-2018b is unavailable

---

pipeline.sh
pipeline_annotate.sh
pipeline_filter.sh
pipeline_preprocess.sh
pipeline_report.sh

Annotation module still has issues with paths containing spaces due to issues in CADD.sh
None.

Fix #51 Pipeline fails for paths with spaces

---

plugins/vep/PreferredTranscript.pm

VEP plugin to annotate transcripts with a PREFERRED flag

---

pipeline.sh
pipeline_annotate.sh

Fix #81 --ann_vep broken

---

plugins/vep/PreferredTranscript.pm

Preferred transcript plugin: ignore transcript versions

---

plugins/vep/Hpo.pm

VEP plugin to annotate transcripts with a HPO flag

---

plugins/vep/SpliceAI.pm

from https://github.com/Ensembl/VEP_plugins/blob/release/101/SpliceAI.pm
None.

Add SpliceAI plugin

---

pipeline.sh
test/pipeline_test.sh
utils/header.sh

Fix #77 Write pipeline version and command to output

---

plugins/vep/Hpo.pm

Fix #97 HPO plugin incorrect if genes_to_phenotype.txt has three cols

---

plugins/vep/Inheritance.pm

Add flag to switch hpo inheritance annotation on.

---

README.md
pipeline.sh
pipeline_preprocess.sh
pipeline_report.sh

Add arguments to pass onto preprocessing or report

---

utils/header.sh

https://github.com/samtools/bcftools/releases/tag/1.11
https://github.com/samtools/htslib/releases/tag/1.11
None.

Update BCFtools, HTSlib and PythonPlus deps

---

utils/header.sh

Latest version is in beta according to @RoanKanninga
None.

Revert PythonPlus dependency update

---

pipeline_preprocess.sh

Fix #116 Filter records with hom_ref/missing for all probands/samples

---

README.md
pipeline.sh

Add option to start pipeline from different starting point

---

utils/header.sh

Report version bump (1.6.0)

---

plugins/vep/Vibe.pm

Add Vibe VEP plugin

---

pipeline_inheritance.sh

remove INFO/ModelScore after inheritance matching is done.

---

pipeline_inheritance.sh

- [n.a.] Documentation was updated
None.

Add non penetrance argument for Genmod

---

pipeline_annotate.sh
pipeline_filter.sh
pipeline_preprocess.sh
utils/utils.sh

Support structural variants

---

pipeline_preprocess.sh
utils/utils.sh

Fix #80 Missing DP format header crash

---

pipeline.sh
utils/utils.sh

- [N.A.] Added feature/fix to draft release notes
None.

Fix #125 Inheritance matching check sometimes fails

---

pipeline_annotate.sh
plugins/vep/AnnotSV.pm
utils/header.sh

AnnotSV VEP plugin

---

config/default.cfg
pipeline.sh
pipeline_annotate.sh
pipeline_filter.sh
pipeline_inheritance.sh
pipeline_preprocess.sh
pipeline_report.sh

Default config file

---

config/default.cfg
pipeline.sh
pipeline_annotate.sh
pipeline_filter.sh
pipeline_inheritance.sh
pipeline_preprocess.sh
pipeline_report.sh

Move hardcoded VIBE paths to default.cfg

---

pipeline_annotate.sh
pipeline_preprocess.sh
utils/utils.sh

- [n.a.] Documentation was updated
None.

fix annotsv phenotypes param+ fix annotSv output file bug

---

config/default.cfg
pipeline.sh
pipeline_annotate.sh
pipeline_filter.sh
pipeline_inheritance.sh
pipeline_preprocess.sh
utils/utils.sh

 Fix #111 --start convenience

---

pipeline.sh
pipeline_annotate.sh
pipeline_filter.sh
pipeline_inheritance.sh
pipeline_preprocess.sh
pipeline_report.sh
utils/utils.sh

Add -h --help for all modules

---

pipeline.sh
pipeline_annotate.sh
pipeline_filter.sh
pipeline_inheritance.sh
pipeline_preprocess.sh
pipeline_report.sh

Show error running scripts without args

---

pipeline_annotate.sh

Skip CAPICE if CADD scores file is empty

---

pipeline.sh

fix ouput option for sbatch

---

utils/header.sh

Update vcf-report/v1.8.0-Java-11-LTS to vcf-report/v1.9.0-Java-11-LTS

---

pipeline_annotate.sh
plugins/vep/VKGL.pm

VEP VKGL plugin

---

plugins/vep/VKGL.pm

fix for consensus file format for VKGL VEP plugin

---

utils/header.sh

- [N.A.] Documentation was updated
None.

Bump VIBE and VIP version

---

pipeline_annotate.sh
plugins/vep/Artefact.pm
plugins/vep/Artefacts.pm

Add Artefact VEP plugin

---

pipeline.sh
pipeline_annotate.sh
pipeline_preprocess.sh
pipeline_report.sh
utils/utils.sh

Pass reference sequence to vcf-report

---

utils/header.sh

update VIP_VERSION from 2.2.0 to 2.3.0
None.

Update vcf-report/v2.3.0-Java-11-LTS to vcf-report/v2.4.0-Java-11-LTS

---

pipeline_report.sh

Fix #170 Pipeline creates kEAYeC4skd.vcf.gz files in script directory

---

pipeline_annotate.sh
pipeline_filter.sh
plugins/vep/AnnotSV.pm
utils/header.sh

Bump AnnotSV v2.5 to v3.0.9

---

pipeline_inheritance.sh
utils/header.sh

Replace PythonPlus module with reproducible genmod module

---

plugins/vep/Artefact.pm
plugins/vep/VKGL.pm

 Fix #187 VEP Artefact plugin performance

---

plugins/vep/Artefact.pm
utils/header.sh

Fix #191 artefact plugin broken

---

resources/plugins/Inheritance.pm

Check gene source and add non penetrance bit to Inheritance plugin

---

install.sh
nextflow.config
utils/singularity/build.sh
utils/singularity/def/vcf-report-2.5.2.def

update vcf-report 2.5.1 to 2.5.2

---

README.md
install.sh

install script: add assembly selection

---

modules/annotate.nf
modules/validate.nf
nextflow.config
templates/annotate.sh

configure annotate_vep_plugin_artefact per assembly

---

resources/vep/plugins/VKGL.pm

Fix #201 VKGL plugin: use of uninitialized value $gene_id warnings

---

templates/annotate.sh

AnnotSV error handling

---

resources/vep/plugins/Hpo.pm

Updated description of HPO VEP plugin.

---

install.sh
nextflow.config
utils/singularity/build.sh
utils/singularity/def/vcf-decision-tree-2.0.1.def

decision tree 2.0.1

---

nextflow.config
templates/annotate.sh

set default vep buffer_size to 500, make configurable

---

install.sh
nextflow.config
resources/decision_tree.json
templates/annotate.sh
test/test.sh
utils/create_gnomad_GRCh37.sh
utils/create_gnomad_GRCh38.sh
utils/singularity/build.sh
utils/singularity/def/vcf-decision-tree-2.1.0.def

Update create_gnomad scripts: add nhomalt annotation

---

utils/singularity/build.sh

Remove htslib from build.sh

---

install.sh
nextflow.config
utils/singularity/build.sh
utils/singularity/def/gatk-4.2.5.0.def

update GATK 4.2.4.1 to 4.2.5.0 (and add performance fix)

---

install.sh
nextflow.config

Update VKGL resources from sep2021 to dec2021

---

install.sh
nextflow.config
utils/singularity/build.sh
utils/singularity/def/vcf-decision-tree-2.2.0.def

feat: update vcf-decision-tree v2.1.0 to v2.2.0

---

install.sh
nextflow.config
utils/singularity/build.sh
utils/singularity/def/vcf-inheritance-matcher-2.0.1.def

fix: bump inheritance matcher v2.0.0 to v2.0.1

---

main.nf
modules/filterInheritance.nf
nextflow.config
templates/filterInheritance.sh
test/resources/snv_proband_trio.vcf

feat: M8703 Optional inheritancematch filtering.

---

install.sh
nextflow.config
test/test.sh
utils/singularity/build.sh
utils/singularity/def/vcf-decision-tree-2.2.1.def

bump decision tree version to v2.2.1

---

install.sh
nextflow.config
utils/singularity/build.sh
utils/singularity/def/vcf-report-4.0.0.def

- [n.v.t.] Documentation was updated
None.

vcf-report 4.0.0 + version bump to 4.20

---

install.sh
modules/annotate.nf
nextflow.config
resources/decision_tree.json
resources/decision_tree_pick.json
templates/annotate.sh
test/test.sh
utils/singularity/build.sh
utils/singularity/def/vcf-decision-tree-3.1.0.def

feat:ClinVar annotation from custom annotation files

---

install.sh
nextflow.config
utils/create_inheritance.sh
utils/singularity/def/capice-3.2.0.def
utils/singularity/def/utils/vcf-inheritance-3.0.0.def

```
$ ml nextflow; bash test/test_wrapper.sh
PASSED test_snv
PASSED test_sv
PASSED test_lp
PASSED test_lb
```

Update HPO, Inheritance and CAPICE

---

install.sh
nextflow.config
utils/singularity/build.sh
utils/singularity/def/vcf-decision-tree-3.2.2.def

fix:bump vcf-decision-tree 3.2.1 to 3.2.2

---

nextflow.config
templates/classify.sh
templates/classify_samples.sh
templates/inheritance.sh
templates/report.sh

Add TMPDIR to singularity bindings by default

---

nextflow.config
resources/vep/plugins/Grantham.pm
templates/annotate.sh

Add Grantham plugin to VIP

---

resources/vep/plugins/AnnotSV.pm
resources/vep/plugins/Artefact.pm

Update supported featureTypes for AnnotSv and Artefact plugin

---

install.sh
nextflow.config
utils/singularity/build.sh
utils/singularity/def/vcf-decision-tree-3.3.0.def

chore:bump version 4.6.0 to 4.7.0
None.

feat:bump vcf-decision-tree 3.2.3 to 3.3.0

---

install.sh
nextflow.config
utils/singularity/build.sh
utils/singularity/def/vcf-decision-tree-3.3.1.def

Bump tree version to 3.3.1 and vip version 4.7.1

---

test/resources/corner_cases.vcf
test/test.sh

Add corner cases integration test

---

install.sh
nextflow.config
utils/singularity/build.sh
utils/singularity/def/vcf-inheritance-matcher-2.0.2.def

fix(deps):bump vcf-inheritance-matcher 2.0.1 to 2.0.2

---

resources/vep/plugins/Artefact.pm
resources/vep/plugins/Hpo.pm
resources/vep/plugins/Inheritance.pm
resources/vep/plugins/VKGL.pm

Add resource files for VEP plugins to vcf headers

---

install.sh
nextflow.config
utils/singularity/build.sh
utils/singularity/def/vcf-report-4.1.4.def

bump vcf-report 4.1.3 to 4.1.4 & build.sh fix

---

templates/filter.sh

fix:filter classes with one class (closes #274)

---

nextflow.config
templates/report.sh

fix:disable cram lzma/bzip2 compression

---

install.sh
test/test.sh

```
$ bash test/test_wrapper.sh
PASSED test_snv
PASSED test_sv
PASSED test_lp
PASSED test_lb
```

Install Nextflow

---

install.sh
nextflow.config
utils/singularity/build.sh
utils/singularity/def/vcf-report-5.1.0.def

Bump vcf-report to 5.1.0

---

.gitignore

Update .gitignore: add nextflow

---

install.sh
nextflow.config
utils/singularity/build.sh
utils/singularity/def/vcf-report-5.1.2.def

Update vip report version (5.1.2)

---

install.sh
test/test.sh

chore(deps):update nextflow 22.10.0 to 22.10.2

---

config/nxf_cram.config
modules/cram/deepvariant.nf
modules/cram/templates/deeptrio_call.sh
modules/cram/templates/deeptrio_call_duo_father.sh
modules/cram/templates/deeptrio_call_duo_mother.sh
vip_cram.nf

WIP duo/trio branching

---

config/nxf_vcf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/vcf-decision-tree-3.5.0.def

this PR is meant to stage these changes to the prototype branch until the download server is back online.

Bump decision tree to 5.3.0

---

config/nxf.config
config/nxf_vcf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/utils/vcf-inheritance-3.0.1.def
utils/apptainer/def/vcf-decision-tree-3.5.1.def
utils/apptainer/def/vcf-inheritance-matcher-2.1.4.def
utils/apptainer/def/vcf-report-5.1.5.def
utils/create_inheritance.sh

Bump dependencies

---

install.sh
utils/apptainer/build.sh
vip.sh

 Fix #321 workaround for bash 4.4-rc1 to bash 5.1-alpha bug

---

config/nxf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/vcf-report-5.2.0.def

feat:bump vcf-report 5.1.6 to 5.2.0

---

config/nxf.config
config/nxf_vcf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/vcf-decision-tree-3.5.2.def
utils/apptainer/def/vcf-inheritance-matcher-2.1.5.def
utils/apptainer/def/vcf-report-5.2.1.def

Update vcf-report, vcf-inheritance-matcher, vcf-decision-tree

---

config/nxf_cram.config
docs/home/key_features.md
docs/usage/config.md
docs/usage/input.md
modules/cram/clair3.nf
modules/fastq/minimap2.nf
test/resources/fastq_nanopore.tsv
test/resources/fastq_pacbio_hifi.tsv
test/test_fastq.sh
vip_cram.nf
vip_fastq.nf

```
PASSED fastq_pacbio_hifi
```

PacBio HiFi support

---

modules/vcf/merge_gvcf.nf
modules/vcf/templates/merge_gvcf.sh

Fix #344 merge_vcf proces can fail with GLnexus merge error

---

modules/cram/publish.nf
vip_cram.nf

Publish vcf result from cram workflow

---

resources/vep/plugins/AnnotSV.pm

Fix #360 AnnotSV annotations missing or invalid

---

test/resources/cram_nanopore.tsv
test/test_cram.sh

Add cram nanopore test

---

config/nxf_cram.config
install.sh
utils/apptainer/build.sh

Bump Clair3 v1.0.0 to v1.0.1

---

config/nxf_vcf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/glnexus_v1.4.5-patched.txt

```
cram tests: pass
vcf tests: pass
```

Update glnexus from 1.4.1 to 1.4.5-patched

---

utils/apptainer/def/utils/seqtk-1.4.def

Bump Seqtk 1.3 to 1.4

---

utils/apptainer/def/utils/crossmap-0.6.5.def
utils/create_genes.txt

Bump CrossMap 0.6.1 to 0.6.5

---

config/nxf_cram.config
install.sh
utils/apptainer/build.sh

Update Clair3 v1.0.1 to v1.0.2

---

modules/cram/cutesv.nf
modules/cram/templates/cutesv_merge.sh
test/resources/cram_nanopore_duo.tsv
test/test_cram.sh
vip_cram.nf

```
PASSED cram_nanopore_duo
```

Fix #391 concat_vcf input file name collision

---

config/nxf_vcf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/build/ubuntu-22.04.def
utils/apptainer/def/samtools-1.17-patch1.def

```
PASSED cram_nanopore_duo
PASSED bam
PASSED cram
PASSED cram_multiproject
PASSED cram_trio
```

Fix #389 samtools markdup can fail

---

modules/cram/templates/cutesv_call.sh
vip_cram.nf

PASSED cram_nanopore_duo
PASSED bam
PASSED cram
PASSED cram_multiproject
PASSED cram_trio

CuteSV workarounds - part I

---

install.sh
utils/apptainer/build.sh
utils/apptainer/def/vcf-report-5.4.0.def

[umcg-bcharbon@gearshift test]$ bash ./test_vcf.sh 
PASSED gvcf
PASSED test_lp
PASSED test_lb

Bump vip-report to 5.4.0

---

config/nxf.config

Bump vip version 5.6.0

---

docs/about/acknowledgements.md

Test doc deployment

---

docs/about/acknowledgements.md

Revert "Test doc deployment"

---

config/nxf_cram.config
config/nxf_vcf.config
docs/about/acknowledgements.md
docs/usage/config.md
docs/usage/workflow.md
install.sh
modules/cram/expansionhunter.nf
modules/cram/templates/expansionhunter_call.sh
utils/apptainer/build.sh
utils/apptainer/def/expansionhunter-5.0.0.def
vip_cram.nf

```
PASSED cram_nanopore_duo
PASSED bam
PASSED cram
PASSED cram_multiproject
PASSED cram_trio
```

Expansion hunter

---

modules/cram/templates/cutesv_call.sh

PASSED fastq_pacbio_hifi
PASSED fastq_nanopore
PASSED fastq_illumina_pairedend
PASSED fastq_illumina_pairedend_trio

Workaround for N in REF of cuteSV

---

.github/workflows/main.yml
mkdocs.yml

Docs fixes

---

README.md
docs/about/license.md

docs:describe relationship to other licences

---

modules/vcf/templates/report.sh

Fix disable/enable cram feature

---

config/nxf.config

bump version

---

config/nxf_vcf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/vcf-report-5.5.2.def

Bump vcf-report to 5.5.2

---

config/nxf.config

Update nxf.config: fix VIP_VERSION

---

modules/vcf/templates/annotate.sh

cram_multiproject test now passes

Fix #432 annotate can fail with 'Failed to instantiate plugin GADO'

---

modules/cram/templates/clair3_call.sh
modules/cram/templates/cutesv_call.sh

Fix #431 'Chromosome blocks not continuous' error

---

modules/cram/validate.nf
vip_vcf.nf

Small fixes (stubbing params, cram param in VCF workflow)

---

config/nxf_vcf.config
install.sh
modules/vcf/annotate.nf
modules/vcf/templates/annotate.sh
test/resources/corner_cases.vcf
utils/apptainer/build.sh
utils/apptainer/def/stranger-0.8.1.def

Add Stranger for str annotation

---

config/nxf_vcf.config
install.sh

bump vkgl_consensus_20230401 to vkgl_consensus_20230701

---

test/test_gvcf.sh

Update test_gvcf.sh: enable test

---

config/nxf_vcf.config
docs/about/acknowledgements.md
docs/advanced/annotations.md
install.sh
modules/vcf/annotate.nf
modules/vcf/templates/annotate.sh
resources/vep/plugins/AlphScore.pm

Add AlphScores to VIP

---

modules/cram/clair3.nf
modules/cram/templates/clair3_joint_call.sh
modules/gvcf/merge.nf
modules/gvcf/templates/merge.sh
modules/gvcf/utils.nf
subworkflows/call_snv_clair3.nf
vip_gvcf.nf
vip_vcf.nf

fix GLnexus memory usage: stick to limits and parallelize

---

resources/vep/plugins/GADO.pm

Fix GADO warning, small improvements

---

config/nxf_vcf.config
install.sh
modules/vcf/annotate.nf
modules/vcf/templates/annotate.sh
resources/vep/plugins/AlphScore.pm
utils/create_alphscore.sh

```
$ bash test_vcf.sh
PASSED test_lp
PASSED test_lb
```

Improve AlphScore VEP plugin performance, fix VKGL GRCh38 resource

---

modules/sample_sheet.nf

additional sample validation rules

---

modules/cram/templates/deepvariant_call.sh

Fix possible deepvariant tmp dir error

---

config/nxf_call_snv.config
config/nxf_gvcf.config
docs/usage/config.md
subworkflows/call_snv_deepvariant.nf
vip_gvcf.nf

Change .g.vcf merge preset default to 'DeepVariant'

---

test/test_cram.sh
test/test_fastq.sh
test/test_gvcf.sh
test/test_vcf.sh

Log test error messages to console

---

modules/cram/deepvariant.nf

Do not publish intermediate deep variant chunked vcfs

---

config/nxf_call_snv.config
docs/usage/config.md
modules/cram/deepvariant.nf
subworkflows/call_snv_deepvariant.nf

Configure GLnexus preset per sequencing method

---

modules/gvcf/templates/validate.sh
modules/gvcf/validate.nf
modules/vcf/templates/validate.sh
modules/vcf/validate.nf

Validate that input contigs exist in reference

---

modules/vcf/annotate.nf
modules/vcf/gado.nf
modules/vcf/templates/annotate.sh
modules/vcf/templates/gado.sh
vip_vcf.nf

Run GADO only once per project

---

utils/create_mmi_GRCh37.sh
utils/create_mmi_GRCh38.sh

util scripts: create reference sequence mmi

---

config/nxf_call_sv.config
docs/usage/config.md
modules/cram/manta.nf
modules/cram/templates/manta_joint_call.sh
modules/cram/templates/validate.sh
modules/cram/validate.nf
subworkflows/call_sv.nf

```
$ bash test.sh --test cram/single,cram/trio
cram/single                              | PASSED | 142269=completed output/cram/single/.nxf.log
cram/trio                                | PASSED | 142270=completed output/cram/trio/.nxf.log
done
```

Manta joint SV calling

---

modules/vcf/templates/annotate.sh

Update annotate.sh: fix GADO plugin call

---

modules/vcf/gado.nf

Update gado.nf: fix stub

---

README.md

Update README.md: fix usage

---

modules/fastq/templates/merge_cram.sh

Merge crams based on filelist

---

config/nxf_vcf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/vcf-report-5.7.0.def

Bump vip-report to 5.7.0

---

docs/get_started/requirements.md

update requirements: require GNU-based Linux

---

resources/vep/plugins/AnnotSV.pm
resources/vep/plugins/GADO.pm
resources/vep/plugins/Hpo.pm
resources/vep/plugins/Inheritance.pm
resources/vep/plugins/VKGL.pm
resources/vep/plugins/ncER.pm

```
$ bash test/test.sh -t vcf
vcf/corner_cases                         | PASSED | 163726=completed test/output/vcf/corner_cases/.nxf.log
vcf/empty_input                          | PASSED | 163727=completed test/output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 163728=completed test/output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 163729=completed test/output/vcf/empty_output_filter/.nxf.log
vcf/filter_samples                       | PASSED | 163730=completed test/output/vcf/filter_samples/.nxf.log
vcf/multiproject_classify                | PASSED | 163731=completed test/output/vcf/multiproject_classify/.nxf.log
vcf/trio                                 | PASSED | 163732=completed …
```

Update (variant) feature types in annotation plugins

---

docs/about/acknowledgements.md

docs: added capice to acknowledgements

---

mkdocs.yml

Update mkdocs.yml: fix site_url and edit_uri

---

modules/cram/templates/cutesv_call.sh

Fix cuteSV workaround

---

resources/decision_tree_samples.json

Update inheritance match node: gene must match

---

config/nxf_vcf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/utils/vcf-inheritance-3.2.0.def
utils/apptainer/def/vcf-report-5.9.0.def
utils/create_inheritance.sh

vcf/corner_cases                         | PASSED | 184500=completed output/vcf/corner_cases/.nxf.log
vcf/empty_input                          | PASSED | 184501=completed output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 184502=completed output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 184503=completed output/vcf/empty_output_filter/.nxf.log
vcf/filter_samples                       | PASSED | 184504=completed output/vcf/filter_samples/.nxf.log
vcf/liftover                             | PASSED | 184505=completed output/vcf/liftover/.nxf.log
vcf/multiproject_classify                | PASSED | 184506=completed …

Update versions to support YL and MT inheritance

---

config/nxf_fastq.config
test/suites/giab/AshkenazimTrio_illumina_wes.sh
test/suites/giab/resources/AshkenazimTrio_illumina_wes.cfg
test/suites/giab/resources/AshkenazimTrio_illumina_wes.tsv
test/test.sh

```
giab/AshkenazimTrio_illumina_wes         | PASSED | 184449=completed test/output/giab/AshkenazimTrio_illumina_wes/.nxf.log
done
```

GIAB Illumina WES test case + configuration process updates

---

config/nxf.config
vip.sh

```
vcf/mvid                                 | PASSED | 187368=completed test/output/vcf/mvid/.nxf.log
done
```
```
[umcg-dhendriksen@betabarrel cli_version]$ ./vip -v
7.3.0
[umcg-dhendriksen@betabarrel cli_version]$ ./vip --version
7.3.0
```

feat:add vip.sh -v, --version

---

config/nxf_vcf.config
install.sh
modules/vcf/classify.nf
modules/vcf/classify_samples.nf
modules/vcf/report.nf
modules/vcf/templates/classify.sh
modules/vcf/templates/classify_samples.sh
modules/vcf/templates/report.sh
resources/field_metadata.json
utils/apptainer/build.sh
utils/apptainer/def/vcf-decision-tree-4.0.0.def
utils/apptainer/def/vcf-inheritance-matcher-3.0.2.def
utils/apptainer/def/vcf-report-6.0.0.def

```
vcf/aip                                  | PASSED | 190601=completed test/output/vcf/aip/.nxf.log
vcf/chd7                                 | PASSED | 190602=completed test/output/vcf/chd7/.nxf.log
vcf/corner_cases                         | PASSED | 190603=completed test/output/vcf/corner_cases/.nxf.log
vcf/deb_register                         | PASSED | 190604=completed test/output/vcf/deb_register/.nxf.log
vcf/empty_input                          | PASSED | 190605=completed test/output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 190606=completed test/output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 190607=completed test/output/vcf/empty_output_filter/.nxf.log …
```

Params to customize classification and reporting metadata

---

resources/decision_tree_GRCh38.json

change tree order to `filter->vkgl->clinvar->gene->chrom`

---

vip.sh

Bump vip version 7.4.0

---

modules/cram/templates/joint_call.sh
modules/gvcf/templates/merge.sh

```
cram/complex                             | PASSED | 199588=completed output/cram/complex/.nxf.log
cram/multiproject                        | PASSED | 199589=completed output/cram/multiproject/.nxf.log
cram/nanopore_duo                        | PASSED | 199590=completed output/cram/nanopore_duo/.nxf.log
cram/nanopore                            | PASSED | 199591=completed output/cram/nanopore/.nxf.log
cram/single                              | PASSED | 199592=completed output/cram/single/.nxf.log
cram/trio                                | PASSED | 199593=completed output/cram/trio/.nxf.log
gvcf/liftover                            | PASSED | 199844=completed output/gvcf/liftover/.nxf.log
gvcf/multiproject                        | PASSED | 199845=completed …
```

Fix incorrect ALT allele order after BCFtools merge

---

docs/examples/reanalysis.md
docs/help/frequently_asked_questions.md

Add FAQ for missing read coverage for SV's

---

docs/examples/reanalysis.md

Remove broken link in documentation

---

docs/index.md

- [n.a.] `APPTAINER_BIND=$PWD bash test/test.sh` passes

docs:add link to vip web interface

---

install.sh
utils/install.sh

fix:install.sh re-installs inheritance resource

---

docs/index.md

doc:add preprint link

---

config/nxf_call_str.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/straglr-1.4.4_vip_v2.def

cram/nanopore_duo                        | PASSED | 214132=completed output/cram/nanopore_duo/.nxf.log
cram/nanopore                            | PASSED | 214133=completed output/cram/nanopore/.nxf.log

Update straglr to v2

---

utils/install.sh

install.sh: suppress git detached head message

---

config/nxf_call_snv.config
config/nxf_cram.config

update default process values for deepvariant_call_duo/trio and coverage

---

vip.sh

update NXF_JVM_ARGS: change -Xmx250m to -Xmx512m

---

docs/usage/config.md
modules/sample_sheet.nf
subworkflows/call_str.nf
test/suites/cram/resources/complex.cfg
test/suites/cram/resources/complex.tsv
test/suites/cram/resources/nanopore.tsv
vip_cram.nf
vip_fastq.nf

cram/complex                             | PASSED | 241551=completed output/cram/complex/.nxf.log
cram/multiproject                        | PASSED | 241552=completed output/cram/multiproject/.nxf.log
cram/nanopore_duo                        | PASSED | 241553=completed output/cram/nanopore_duo/.nxf.log
cram/nanopore                            | PASSED | 241554=completed output/cram/nanopore/.nxf.log
cram/single                              | PASSED | 241555=completed output/cram/single/.nxf.log
cram/trio                                | PASSED | 241556=completed output/cram/trio/.nxf.log

Add "pcr_performed" param to disable incompatible tools

---

modules/vcf/utils.nf
test/suites/vcf/trio.sh

Fix GADO not working with certain hpo / proband combinations

---

vip.sh

Bump vip version to 7.9.0

---

modules/cram/templates/straglr_call.sh

Fix #634 Sex not passed to Straglr

---

config/nxf_vcf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/vcf-inheritance-matcher-3.1.1.def
vip.sh

update inheritance matcher 3.1.1

---

.travis.yml

Fix pages deploy via travis

---

.travis.yml

Fix docs deploy at travis attempt 2

---

config/nxf_vcf.config
install.sh
resources/decision_tree_GRCh38.json
resources/field_metadata.json

fix:set STR_STATUS metadata to PER_ALT

---

config/nxf_vcf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/vcf-decision-tree-5.1.2.def

Chore/bump decision tree5.1.2

---

docs/usage/input.md
vip_fastq.nf

Replace Illumina with nanopore as default sequencing platform

---

config/nxf_cram.config

fix:coverage out-of-memory

---

modules/vcf/templates/annotate.sh

Calculate and annotate VIAB

---

config/nxf_vcf.config
install.sh

Bump template to 7.1.0

---

config/nxf_vcf.config
install.sh
modules/vcf/templates/annotate.sh
utils/apptainer/build.sh
utils/apptainer/def/stranger-0.9.3.def
utils/apptainer/def/vcf-decision-tree-5.1.3.def

Update stranger, decision-tree and fix 'division by zero' in annotate

---

config/nxf.config
config/nxf_call_cnv.config
config/nxf_call_snv.config
config/nxf_call_str.config
config/nxf_call_sv.config
config/nxf_fastq.config
config/nxf_vcf.config
utils/create_gnomad.sh
utils/create_inheritance.sh
utils/create_mmi.sh

```
vcf/trio                                 | PASSED | 334235=completed test/output/vcf/trio/.nxf.log
done
```

Fix apptainer bind warnings

---

docs/usage/config.md

docs:update config process section

---

config/nxf_call_snv.config

Increase whatshap memory requirements from default 4GB to 16GB

---

docs/advanced/classification_trees.md

Small improvements to decision tree docs

---

docs/usage/input.md
docs/usage/output.md
docs/usage/workflow.md

docs: Fixed list of live example numberings.

---

docs/usage/workflow.md

Fix documentation, sup 1 missing for whatshap

---

docs/get_started/installation.md
install.sh
install_data.sh

Add prune option to install script

---

config/nxf_vcf.config
docs/get_started/installation.md
install.sh
install_data.sh
utils/apptainer/build.sh
utils/apptainer/def/vcf-decision-tree-5.1.4.def
utils/apptainer/def/vcf-report-7.2.2.def
vip.sh

```
cram/complex                             | PASSED | 370713=completed vip/bump_dependencies/test/output/cram/complex/.nxf.log
cram/multiproject                        | PASSED | 370714=completed vip/bump_dependencies/test/output/cram/multiproject/.nxf.log
cram/nanopore_duo                        | PASSED | 370715=completed vip/bump_dependencies/test/output/cram/nanopore_duo/.nxf.log
cram/nanopore                            | PASSED | 370716=completed vip/bump_dependencies/test/output/cram/nanopore/.nxf.log
cram/single                              | PASSED | 370717=completed vip/bump_dependencies/test/output/cram/single/.nxf.log
cram/trio                                | PASSED | 370718=completed vip/bump_dependencies/test/output/cram/trio/.nxf.log …
```

Update vcf-decision-tree, vcf-report-template and vcf-report

---

install.sh

docs: fix script name in usage

---

resources/field_metadata.json
resources/vep/plugins/GREEN_DB.pm

Adjusted vep plugin for GREEN-DB
Added field to field_metadata.json

Adjusted VEP plugin to annotate "controlled_genes"

---

test/suites/giab/resources/AshkenazimTrio_pacbio_ccs.cfg

do not include crams for pacbio GIAB test

---

docs/usage/config.md

remove invalid key from config doc

---

docs/get_started/installation.md
install.sh

make --version undocumented developer function

---

modules/vcf/templates/annotate.sh

Before submitting this PR, please make sure:

refactor: remove duplicate cli arg from vep annotate call
