molgenis/vip

pipeline.sh
pipeline_annotate.sh
pipeline_filter.sh
pipeline_preprocess.sh
pipeline_report.sh

- Added quotes to variables inside if statements ([argument](https://tldp.org/LDP/abs/html/quotingvar.html): "When referencing a variable, it is generally advisable to enclose its name in double quotes.")
- Places that called a `sh`, `java` and alike, variables were not enclosed as this might break stuff.
- Replaced `echo` that included a literal new line to `echo -e` with a `\n` ([source](https://unix.stackexchange.com/a/189819), argument: cleaner code)
- Replaced "setting a default if no user-input was given after user-input digestion" to "set default at the top of the script where variable is declared" (argument: removes possible initial confusion when viewing scripts what the defaults are, if there are any)
- Removed a `\` at the end of the line of a Python execution where no …

Code improvements.

---

utils/header.sh

- [will test when v1.1.x is available] Functionality works & meets specs
- [will test when v1.1.x is available] No issues running `sh test/pipeline_test.sh`
- [N.A] Documentation was updated
None.

Fix #65 Use CADD/v1.4-foss-2018b-minimal when available (backport)

---

utils/header.sh

Update vcf-inheritance-matcher/v0.0.3-Java-11-LTS to v0.1.0

---

pipeline.sh
pipeline_annotate.sh
pipeline_filter.sh
pipeline_inheritance.sh
pipeline_preprocess.sh
pipeline_report.sh

Fix #129 CADD should use TMPDIR instead of /tmp

---

pipeline_annotate.sh

Fix annotation in case of no CADD scores for CAPICE variants

---

.gitignore
README.md
Vagrantfile

- Added `Vagrantfile`.
- Updated README.
- Updated `.gitignore`.
`Vagrantfile` supports building (and running individual images if required data is present), `pipeline.sh` and similar scripts do not run due to lacking `/apps` folder. This is mentioned in the README.

Added Vagrantfile to easily allow building `.sif` files on MacOS.

---

resources/vep/plugins/Capice.pm

When there are empty fields at the end of a capice output line, no tabs are added.
This leads to the VEP plugin complaining about using undefined fields for a concatenation (e.g. 'feature'/'feature_type' fields)
None.

Fix multiple CAPICE VEP plugin issues

---

resources/decision_tree.json

```
PASSED test_snv
PASSED test_sv
PASSED test_lp
PASSED test_lb
```

fix: remove CAPICE from default decision tree

---

resources/decision_tree.json

Introduce default filter tree exit state for unclassified variants (e.g. filter != PASS).

---

nextflow.config

'classify_samples' missing in the nextflow config, therefor running with only 100MB memory

---

install.sh
nextflow.config

- Added support for the version 2 models of CAPICE 4.0.0 (no heterozygous variants in AR genes)
None.

feat: CAPICE 4.0.0 V2 support

---

install.sh

fix: install.sh creates empty files on wget error

---

README.md

I would like to see links to simple examples high up in the manual so the most common use cases give me a samplesheet to start from. Are there useful sheets to point to in this folder? 
https://github.com/molgenis/vip/tree/main/test/resources
Meanwhile made links within the readme.

docs: add links from config to examples

---

config/nxf_vcf.config

fix:remove unused vcf.report.bams param

---

config/nxf.config
config/nxf_vcf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/vcf-report-5.1.6.def

chore:bump vcf-report 5.1.5 to 5.1.6

---

config/nxf.config
modules/cram/clair3.nf
modules/cram/templates/clair3_call.sh

Fix #322 Cram workflow can fail in case of 'B' nucleotide in reference

---

modules/cram/templates/clair3_call.sh

Workaround for clair3 cram issue

---

modules/cram/templates/sniffles2_call.sh

fix:remove call to undefined stats function in sniffles2_call.sh

---

modules/vcf/templates/merge_gvcf.sh

```
[umcg-dhendriksen@gearshift test]$ bash test.sh
PASSED gvcf
PASSED test_lp
PASSED test_lb
PASSED bam
PASSED cram
PASSED cram_multiproject
PASSED cram_trio
PASSED fastq_pacbio_hifi
```

fix:reheader workaround

---

config/nxf_vcf.config

fix:SAMtools can connect to EBI

---

modules/vcf/templates/annotate.sh

Fail VIP on failure of VEP plugin

---

utils/apptainer/def/utils/vcf-inheritance-3.1.2.def
utils/create_inheritance.sh

bump vcf-inheritance 3.1.0 to 3.1.2

---

modules/cram/templates/manta_call.sh

Fix #367 Workaround for VEP out-of-memory errors

---

config/nxf_vcf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/vcf-decision-tree-3.5.4.def

```
PASSED gvcf
PASSED test_lp
PASSED test_lb
```

fix:bump vcf-decision-tree 3.5.3 to 3.5.4

---

config/nxf_cram.config
modules/cram/templates/clair3_call.sh

Cram tests in progress...
----
To enable 'retry' after https://github.com/HKU-BAL/Clair3/issues/200
Manual test of this construction with a vcf containing as described in the clair3 issue:
`bcftools view /invalid.vcf.gz  > /dev/null`
```
[E::vcf_parse_format] Invalid character 'c' in 'PL' FORMAT field at chr1:1234
Error: VCF parse error
```
Retry config tested with an `exit 1` in the "validate()"

Validate vcf after clair3 run

---

config/nxf_vcf.config
install.sh
modules/vcf/templates/annotate.sh
utils/convert_phylop_to_bed.txt

```
PASSED gvcf
PASSED test_lp
PASSED test_lb
```

Fix #385 VEP out-of-memory workaround: replace bigWig with bed

---

modules/vcf/templates/annotate.sh

- [nvt] Updated documentation 
PASSED gvcf
PASSED test_lp
PASSED test_lb

Fix awk command in annotSV workaround

---

config/nxf_vcf.config

bash ./test_vcf.sh
PASSED gvcf
PASSED test_lp
PASSED test_lb

Update apptainer cmd for vip-report 5.4.0

---

vip.sh

Use nextflow environment variables if already exist

---

config/nxf.config
config/nxf_vcf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/vcf-report-5.4.1.def

bump vcf-report-5.4.0 to vcf-report-5.4.1

---

config/nxf.config
config/nxf_vcf.config
docs/usage/input.md
install.sh
utils/apptainer/build.sh
utils/apptainer/def/vcf-report-5.5.1.def

bump vcf-report to 5.5.1, fix project_id param documentation

---

config/nxf.config

Add default error strategy with backoff

---

install.sh

fix:install correct hpo resource

---

resources/vep/plugins/GADO.pm

fix GADO VEP plugin: NPE in print statement

---

config/nxf_vcf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/vcf-inheritance-matcher-2.1.7.def

bump vcf-inheritance-matcher 2.1.6 to 2.1.7

---

resources/vep/plugins/AnnotSV.pm
resources/vep/plugins/Capice.pm
resources/vep/plugins/VKGL.pm

This leads to loss of data from VEP if an empty result is returned by the plugin

Fix VEP plugins returning () instead of {}

---

install.sh

Fix filename for AlphScore resource

---

.gitignore

Fix gitignore for vep plugins

---

config/nxf.config

chore:bump version v5.8.2 to v6.0.0

---

utils/create_inheritance.sh

Fix create_inheritance.sh: update incomplete penetrance file path

---

modules/vcf/report.nf

fix #467 Report with long-read alignment hangs

---

config/nxf_call_str.config
install.sh
modules/cram/straglr.nf
modules/cram/templates/straglr_call.sh
utils/apptainer/build.sh
utils/apptainer/def/straglr-philres-1.4.2.def

 Fix #471 cram_str_straglr_call can produce unsorted vcf

---

modules/cram/templates/deepvariant_call.sh

Fix possible deepvariant tmp dir error

---

install.sh

fix: revert removal of unzip_reference

---

modules/vcf/annotate.nf

```
vcf/corner_cases                         | PASSED | 145571=completed output/vcf/corner_cases/.nxf.log
vcf/empty_input                          | PASSED | 145572=completed output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 145573=completed output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 145574=completed output/vcf/empty_output_filter/.nxf.log
vcf/lb_b38                               | PASSED | 145575=completed output/vcf/lb_b38/.nxf.log
vcf/lb                                   | PASSED | 145576=completed output/vcf/lb/.nxf.log
vcf/lp_b38                               | PASSED | 145577=completed output/vcf/lp_b38/.nxf.log
vcf/lp                                   | PASSED | …
```

Update annotate.nf: fix GADO

---

modules/fastq/utils.nf

Fix: non paired ended fastq split broken

---

test/suites/fastq/nanopore.sh
test/suites/fastq/resources/nanopore.tsv

```
fastq/nanopore                           | PASSED | 158487=completed output/fastq/nanopore/.nxf.log
```

split fastq for non paired ended test

---

modules/fastq/templates/merge_cram.sh
modules/fastq/templates/minimap2_align_paired_end.sh

fastq/nanopore | PASSED |
fastq/pacbio_hifi | PASSED |
manual paired end - multi file per pair - test is now @ variant calling, so past the point of these changes

Run fixmate and sort parallel on crams

---

install.sh
vip.sh

```
vcf/corner_cases                         | PASSED | 159383=completed test/output/vcf/corner_cases/.nxf.log
vcf/empty_input                          | PASSED | 159384=completed test/output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 159385=completed test/output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 159386=completed test/output/vcf/empty_output_filter/.nxf.log
vcf/lb_b38                               | PASSED | 159387=completed test/output/vcf/lb_b38/.nxf.log
vcf/lb                                   | PASSED | 159388=completed test/output/vcf/lb/.nxf.log
vcf/lp_b38                               | PASSED | 159389=completed test/output/vcf/lp_b38/.nxf.log
vcf/lp …
```

update Nextflow 23.04.1 to 23.10.0

---

modules/sample_sheet.nf

create an error in `vcf/snv_proband_trio`:
```
vcf/snv_proband_trio_b38                 | PASSED | 160066=completed test/output/vcf/snv_proband_trio_b38/.nxf.log
vcf/snv_proband_trio_sample_filtering    | PASSED | 160067=completed test/output/vcf/snv_proband_trio_sample_filtering/.nxf.log
vcf/snv_proband_trio                     | KAPUTT | 160068=failed    test/output/vcf/snv_proband_trio/.nxf.log
done
```
```
Nov-09 14:52:43.809 [main] ERROR nextflow.Nextflow - error parsing '/groups/umcg-vipt/tmp05/projects/vip_validation/fix/samplesheet_validation/test/suites/vcf/resources/snv_proband_trio.tsv': line 1: maternal_id sample 'MOTHERx0' for sample 'PROBAND0' is not present in project 'vip'.
```

fix sample sheet project validation

---

config/nxf_vcf.config
install.sh

```
vcf/corner_cases                         | PASSED | 159875=completed test/output/vcf/corner_cases/.nxf.log
vcf/empty_input                          | PASSED | 159876=completed test/output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 159877=completed test/output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 159878=completed test/output/vcf/empty_output_filter/.nxf.log
vcf/lb_b38                               | PASSED | 159879=completed test/output/vcf/lb_b38/.nxf.log
vcf/lb                                   | PASSED | 159880=completed test/output/vcf/lb/.nxf.log
vcf/lp_b38                               | PASSED | 159881=completed test/output/vcf/lp_b38/.nxf.log
vcf/lp …
```

update ClinVar 20230910 to 20231104

---

config/nxf_vcf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/vcf-inheritance-matcher-2.1.9.def

```
vcf/snv_proband_trio_b38                 | PASSED | 160259=completed test/output/vcf/snv_proband_trio_b38/.nxf.log
vcf/snv_proband_trio_sample_filtering    | PASSED | 160260=completed test/output/vcf/snv_proband_trio_sample_filtering/.nxf.log
vcf/snv_proband_trio                     | PASSED | 160261=completed test/output/vcf/snv_proband_trio/.nxf.log
done
```

bump inheritance matcher 2.1.8 to 2.1.9

---

modules/cram/validate.nf
subworkflows/call_snv_deepvariant.nf
subworkflows/call_str.nf
subworkflows/call_sv.nf
vip_cram.nf
vip_vcf.nf

cram/complex                             | PASSED | 165618=completed output/cram/complex/.nxf.log
cram/multiproject                        | PASSED | 165619=completed output/cram/multiproject/.nxf.log
cram/nanopore_duo                        | PASSED | 165620=completed output/cram/nanopore_duo/.nxf.log
cram/nanopore                            | PASSED | 165621=completed output/cram/nanopore/.nxf.log
cram/single                              | PASSED | 165622=completed output/cram/single/.nxf.log
cram/trio                                | PASSED | 165623=completed output/cram/trio/.nxf.log
fastq/nanopore                           | PASSED | 165624=completed output/fastq/nanopore/.nxf.log
fastq/pacbio_hifi …

Fix: crams not reaching the report

---

modules/cram/templates/concat_vcf.sh
modules/cram/templates/straglr_call.sh

Fix bcftools sort --max-mem values

---

modules/cram/templates/cutesv_call.sh

``` 
cram/nanopore_duo                        | PASSED | 172460=completed output/cram/nanopore_duo/.nxf.log
cram/nanopore                            | PASSED | 172461=completed output/cram/nanopore/.nxf.log
fastq/nanopore                           | PASSED | 172464=completed output/fastq/nanopore/.nxf.log
fastq/pacbio_hifi                        | PASSED | 172465=completed output/fastq/pacbio_hifi/.nxf.log
gvcf/liftover                            | PASSED | 172466=completed output/gvcf/liftover/.nxf.log
gvcf/multiproject                        | PASSED | 172467=completed output/gvcf/multiproject/.nxf.log
gvcf/trio                                | PASSED | 172468=completed output/gvcf/trio/.nxf.log
vcf/corner_cases                         | PASSED | 172469=completed …
```

Reintroduce cuteSV workaround

---

modules/cram/templates/expansionhunter_call.sh
test/suites/cram/resources/single.cfg

Workaround for Expansionhunter output missing SVTYPE

---

utils/apptainer/build.sh

Fix #336 build.sh only works if ran from script directory

---

modules/vcf/report.nf

Re-enable long read alignment in report

---

config/nxf.config
config/nxf_vcf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/vcf-report-5.8.1.def

```
$ bash test/test.sh -t vcf -c
vcf/corner_cases                         | PASSED | 181265=completed test/output/vcf/corner_cases/.nxf.log
vcf/empty_input                          | PASSED | 181266=completed test/output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 181267=completed test/output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 181268=completed test/output/vcf/empty_output_filter/.nxf.log
vcf/filter_samples                       | PASSED | 181269=completed test/output/vcf/filter_samples/.nxf.log
vcf/liftover                             | PASSED | 181270=completed test/output/vcf/liftover/.nxf.log
vcf/multiproject_classify                | PASSED | 181271=completed …
```

Bump vcf-report 5.8.0 to 5.8.1

---

modules/cram/deepvariant.nf
test/suites/giab/AshkenazimTrio_pacbio_ccs.sh
test/suites/giab/resources/AshkenazimTrio_pacbio_ccs.cfg

```
giab/AshkenazimTrio_pacbio_ccs           | PASSED | 36608=completed test/output/giab/AshkenazimTrio_pacbio_ccs/.nxf.log
done
```

Fix DeepVariant trio calling out-of-memory errors & GIAB AshkenazimTrio_pacbio_ccs test

---

resources/vep/plugins/Inheritance.pm
resources/vep/plugins/VKGL.pm
resources/vep/plugins/ncER.pm

```
vcf/corner_cases                         | PASSED | 183487=completed test/output/vcf/corner_cases/.nxf.log
vcf/empty_input                          | PASSED | 183488=completed test/output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 183489=completed test/output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 183490=completed test/output/vcf/empty_output_filter/.nxf.log
vcf/filter_samples                       | PASSED | 183491=completed test/output/vcf/filter_samples/.nxf.log
vcf/liftover                             | PASSED | 183492=completed test/output/vcf/liftover/.nxf.log
vcf/multiproject_classify                | PASSED | 183493=completed test/output/vcf/multiproject_classify/.nxf.log …
```

Fix VEP plugin warnings

---

test/suites/cram/complex.sh
test/suites/cram/multiproject.sh
test/suites/cram/nanopore.sh
test/suites/cram/nanopore_duo.sh
test/suites/cram/single.sh
test/suites/cram/trio.sh
test/suites/fastq/nanopore.sh
test/suites/fastq/pacbio_hifi.sh
test/utils.sh

cram/complex                             | PASSED | 187552=completed output/cram/complex/.nxf.log
cram/multiproject                        | PASSED | 187553=completed output/cram/multiproject/.nxf.log
cram/nanopore_duo                        | PASSED | 187554=completed output/cram/nanopore_duo/.nxf.log
cram/nanopore                            | PASSED | 187555=completed output/cram/nanopore/.nxf.log
cram/single                              | PASSED | 187556=completed output/cram/single/.nxf.log
cram/trio                                | PASSED | 187557=completed output/cram/trio/.nxf.log
fastq/nanopore                           | PASSED | 187808=completed output/fastq/nanopore/.nxf.log
fastq/pacbio_hifi …

Add md5sum for all tests

---

resources/vep/plugins/ncER.pm

see BB: 
/groups/umcg-vipt/tmp05/projects/vip_validation/fix/ncer_warnings/test/output/vcf/vkgl_lp/.nxf.work/6a/2d65332fc6fd15bd21ac32f39f3fd8/
for the output log
vcf/aip                                  | PASSED | 191375=completed output/vcf/aip/.nxf.log
vcf/chd7                                 | PASSED | 191376=completed output/vcf/chd7/.nxf.log
vcf/corner_cases                         | PASSED | 191377=completed output/vcf/corner_cases/.nxf.log
vcf/deb_register                         | PASSED | 191378=completed output/vcf/deb_register/.nxf.log
vcf/empty_input                          | PASSED | 191379=completed output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 191380=completed …

Fix: ncER score can be undefined causing warnings in the VEP plugin

---

resources/vep/plugins/GADO.pm
resources/vep/plugins/Hpo.pm

vcf/aip                                  | PASSED | 193482=completed output/vcf/aip/.nxf.log
vcf/chd7                                 | PASSED | 193483=completed output/vcf/chd7/.nxf.log
vcf/corner_cases                         | PASSED | 193484=completed output/vcf/corner_cases/.nxf.log
vcf/deb_register                         | PASSED | 193485=completed output/vcf/deb_register/.nxf.log
vcf/empty_input                          | PASSED | 193486=completed output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 193487=completed output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 193488=completed output/vcf/empty_output_filter/.nxf.log
vcf/filter_samples                       | PASSED | 193489=completed …

Fix plugins for features that do not support transcript

---

modules/vcf/templates/liftover.sh

Reduce memory needed for picard liftover

---

vip.sh

```
fastq/nanopore                           | PASSED | 200242=completed output/fastq/nanopore/.nxf.log
fastq/pacbio_hifi                        | PASSED | 200243=completed output/fastq/pacbio_hifi/.nxf.log
```

Limit memory used by driver job

---

install.sh

Fixes the absence of "nextflow" symlink if changing permissions failed due to the nextflow version already being installed by a different user.

Fix install script for cases that nextflow already exists

---

config/nxf_fastq.config
docs/usage/config.md
install.sh
modules/fastq/minimap2.nf
utils/apptainer/build.sh
utils/apptainer/def/minimap2-2.27.def

fastq/nanopore                           | PASSED | 204484=completed output/fastq/nanopore/.nxf.log
fastq/pacbio_hifi                        | PASSED | 204485=completed output/fastq/pacbio_hifi/.nxf.log
Runs with both presets result in no differences for tested sample:
vaxtron /groups/umcg-gdio/tmp03/umcg-bcharbon/nanopore/minimap/

Update minimap 2.26 -> 2.27 + update preset

---

config/nxf_vcf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/vcf-inheritance-matcher-3.1.0.def
vip.sh

vcf/aip                                  | PASSED | 210296=completed output/vcf/aip/.nxf.log
vcf/chd7                                 | PASSED | 210297=completed output/vcf/chd7/.nxf.log
vcf/corner_cases                         | PASSED | 210298=completed output/vcf/corner_cases/.nxf.log
vcf/deb_register                         | PASSED | 210612=completed output/vcf/deb_register/.nxf.log
vcf/empty_input                          | PASSED | 210300=completed output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 210301=completed output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 210302=completed output/vcf/empty_output_filter/.nxf.log …

VIP 7.6.0 - update inheritance

---

config/nxf_vcf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/vcf-report-6.0.2.def
vip.sh

```
vcf/aip                                  | PASSED | 215047=completed test/output/vcf/aip/.nxf.log
vcf/chd7                                 | PASSED | 215048=completed test/output/vcf/chd7/.nxf.log
vcf/corner_cases                         | PASSED | 215049=completed test/output/vcf/corner_cases/.nxf.log
vcf/deb_register                         | PASSED | 215050=completed test/output/vcf/deb_register/.nxf.log
vcf/empty_input                          | PASSED | 215051=completed test/output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 215052=completed test/output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 215053=completed test/output/vcf/empty_output_filter/.nxf.log …
```

Feat/bump report 6.0.2

---

config/nxf_call_str.config
config/nxf_vcf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/straglr-1.4.4_vip_v3.def
utils/apptainer/def/vcf-decision-tree-4.1.1.def
vip.sh

vcf/aip                                  | PASSED | 218035=completed output/vcf/aip/.nxf.log
vcf/chd7                                 | PASSED | 218036=completed output/vcf/chd7/.nxf.log
vcf/corner_cases                         | PASSED | 218037=completed output/vcf/corner_cases/.nxf.log
vcf/deb_register                         | PASSED | 218038=completed output/vcf/deb_register/.nxf.log
vcf/empty_input                          | PASSED | 218039=completed output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 218040=completed output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 218041=completed output/vcf/empty_output_filter/.nxf.log
vcf/filter_samples                       | PASSED | 218042=completed …

Fix decision tree issues (regarding FLAG and FILE support)

---

modules/vcf/utils.nf

vcf/aip                                  | PASSED | 220315=completed output/vcf/aip/.nxf.log
vcf/chd7                                 | PASSED | 220316=completed output/vcf/chd7/.nxf.log
vcf/corner_cases                         | PASSED | 220317=completed output/vcf/corner_cases/.nxf.log
vcf/deb_register                         | PASSED | 220318=completed output/vcf/deb_register/.nxf.log
vcf/empty_input                          | PASSED | 220319=completed output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 220320=completed output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 220321=completed output/vcf/empty_output_filter/.nxf.log
vcf/filter_samples                       | PASSED | …

Fix null exception when no HPO provided

---

resources/vep/plugins/gnomAD.pm
test/suites/vcf/vkgl_lb.sh

```
vcf/vkgl_lb                              | PASSED | 223534=completed test/output/vcf/vkgl_lb/.nxf.log
vcf/vkgl_lp                              | PASSED | 223535=completed test/output/vcf/vkgl_lp/.nxf.log
done
```

fix gnomAD VEP plugin: gnomAD_QC can be incorrect

---

modules/cram/coverage.nf
modules/cram/templates/coverage.sh
vip_cram.nf
vip_fastq.nf

```
cram/complex                             | PASSED | 225734=completed test/output/cram/complex/.nxf.log
cram/multiproject                        | PASSED | 225735=completed test/output/cram/multiproject/.nxf.log
cram/nanopore_duo                        | PASSED | 225736=completed test/output/cram/nanopore_duo/.nxf.log
cram/nanopore                            | PASSED | 225737=completed test/output/cram/nanopore/.nxf.log
cram/single                              | PASSED | 225738=completed test/output/cram/single/.nxf.log
cram/trio                                | PASSED | 225739=completed test/output/cram/trio/.nxf.log
fastq/nanopore                           | PASSED | 225740=completed test/output/fastq/nanopore/.nxf.log
fastq/pacbio_hifi                        | …
```

Produce cram coverage and read depth intermediate outputs

---

install.sh
utils/install.sh
vip.sh

```
vcf/aip                                  | PASSED | 226457=completed test/output/vcf/aip/.nxf.log
vcf/chd7                                 | PASSED | 226458=completed test/output/vcf/chd7/.nxf.log
vcf/corner_cases                         | PASSED | 226459=completed test/output/vcf/corner_cases/.nxf.log
vcf/deb_register                         | PASSED | 226460=completed test/output/vcf/deb_register/.nxf.log
vcf/empty_input                          | PASSED | 226461=completed test/output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 226462=completed test/output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 226463=completed test/output/vcf/empty_output_filter/.nxf.log …
```

bump Nextflow 23.10.0 to 24.04.2

---

config/nxf_vcf.config
install.sh
utils/apptainer/build.sh
utils/apptainer/def/vcf-report-6.1.0.def

```
vcf/aip                                  | PASSED | 234916=completed test/output/vcf/aip/.nxf.log
vcf/chd7                                 | PASSED | 234917=completed test/output/vcf/chd7/.nxf.log
vcf/corner_cases                         | PASSED | 234918=completed test/output/vcf/corner_cases/.nxf.log
vcf/deb_register                         | PASSED | 234919=completed test/output/vcf/deb_register/.nxf.log
vcf/empty_input                          | PASSED | 234920=completed test/output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 234921=completed test/output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 234922=completed test/output/vcf/empty_output_filter/.nxf.log …
```

bump vip-report 6.0.2 to 6.1.0

---

config/nxf_fastq.config

update fastq config: set 'filter_reads' cpus to 1

---

config/nxf_vcf.config
install.sh
modules/vcf/report.nf
modules/vcf/templates/report.sh
utils/apptainer/build.sh
utils/apptainer/def/vcf-report-7.0.0.def

vcf/aip                                  | PASSED | 242227=completed output/vcf/aip/.nxf.log
vcf/chd7                                 | PASSED | 242228=completed output/vcf/chd7/.nxf.log
vcf/corner_cases                         | PASSED | 242229=completed output/vcf/corner_cases/.nxf.log
vcf/deb_register                         | PASSED | 242230=completed output/vcf/deb_register/.nxf.log
vcf/empty_input                          | PASSED | 242231=completed output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 242232=completed output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 242233=completed output/vcf/empty_output_filter/.nxf.log …

Bump vip report to v7.0.0 (add sample tree to report)

---

test/test.sh

fix test.sh runner: fail on 'TIMEOUT' state

---

modules/fastq/minimap2.nf
test/suites/fastq/nanopore_adaptive_sampling.sh

```
fastq/nanopore_adaptive_sampling         | PASSED | 260926=completed test/output/fastq/nanopore_adaptive_sampling/.nxf.log
done
```
```
[umcg-dhendriksen@betabarrel cram_publish]$ ll test/output/fastq/nanopore_adaptive_sampling/intermediates/
...
-rw-rw-r--. 2 umcg-dhendriksen umcg-vipt  28839397 Aug 21 07:44 vip_fam0_HG002.cram
-rw-rw-r--. 2 umcg-dhendriksen umcg-vipt      1025 Aug 21 07:44 vip_fam0_HG002.cram.crai
-rw-rw-r--. 2 umcg-dhendriksen umcg-vipt      5346 Aug 21 07:44 vip_fam0_HG002.cram.stats
...
```

Fix #632 .cram not published in fastq workflow

---

docs/about/acknowledgements.md
docs/usage/workflow.md
modules/cram/coverage.nf
modules/cram/templates/coverage.sh
vip_cram.nf

cram/complex                             | PASSED | 288394=completed output/cram/complex/.nxf.log
cram/multiproject                        | PASSED | 288395=completed output/cram/multiproject/.nxf.log
cram/nanopore_duo                        | PASSED | 288396=completed output/cram/nanopore_duo/.nxf.log
cram/nanopore                            | PASSED | 288397=completed output/cram/nanopore/.nxf.log
cram/single                              | PASSED | 288398=completed output/cram/single/.nxf.log
cram/trio                                | PASSED | 288399=completed output/cram/trio/.nxf.log
fastq/nanopore_adaptive_sampling         | PASSED | 287196=completed output/fastq/nanopore_adaptive_sampling/.nxf.log …

Calculate coverage using mosdepth and regions file

---

config/nxf.config
install.sh
modules/sample_sheet.nf
test/suites/cram/resources/multiproject.tsv
test/suites/cram/resources/single.tsv
test/suites/cram/resources/trio.tsv
utils/install.sh
vip_cram.nf
vip_fastq.nf
vip_gvcf.nf
vip_vcf.nf

```
cram/complex                             | PASSED | 293890=completed test/output/cram/complex/.nxf.log
cram/multiproject                        | PASSED | 293891=completed test/output/cram/multiproject/.nxf.log
cram/nanopore_duo                        | PASSED | 293892=completed test/output/cram/nanopore_duo/.nxf.log
cram/nanopore                            | PASSED | 293893=completed test/output/cram/nanopore/.nxf.log
cram/single                              | PASSED | 293894=completed test/output/cram/single/.nxf.log
cram/trio                                | PASSED | 293895=completed test/output/cram/trio/.nxf.log
fastq/nanopore_adaptive_sampling         | PASSED | 293896=completed test/output/fastq/nanopore_adaptive_sampling/.nxf.log
fastq/nanopore …
```

feat:sample sheet HPO validation

---

config/nxf_vcf.config
install.sh

```
cram/complex                             | PASSED | 300662=completed test/output/cram/complex/.nxf.log
cram/multiproject                        | PASSED | 300663=completed test/output/cram/multiproject/.nxf.log
cram/nanopore_duo                        | PASSED | 300664=completed test/output/cram/nanopore_duo/.nxf.log
cram/nanopore                            | PASSED | 300665=completed test/output/cram/nanopore/.nxf.log
cram/single                              | PASSED | 300666=completed test/output/cram/single/.nxf.log
cram/trio                                | PASSED | 300667=completed test/output/cram/trio/.nxf.log
fastq/nanopore_adaptive_sampling         | PASSED | 300668=completed test/output/fastq/nanopore_adaptive_sampling/.nxf.log
fastq/nanopore …
```

fix:bump vip-report-template v7.0.2 to v7.0.5

---

config/nxf_vcf.config
install.sh
resources/decision_tree_GRCh38.json

fix:bump vip-report-template v7.0.5 to v7.0.6, improve decision tree exit node labelling

---

.gitignore
install.sh
utils/install.sh
vip.sh

```
vcf/aip                                  | PASSED | 308964=completed test/output/vcf/aip/.nxf.log
vcf/chd7                                 | PASSED | 308965=completed test/output/vcf/chd7/.nxf.log
vcf/corner_cases                         | PASSED | 308966=completed test/output/vcf/corner_cases/.nxf.log
vcf/deb_register                         | PASSED | 308967=completed test/output/vcf/deb_register/.nxf.log
vcf/empty_input                          | PASSED | 308968=completed test/output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 308969=completed test/output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 308970=completed test/output/vcf/empty_output_filter/.nxf.log …
```

feat:bump Nextflow 24.04.2 to 24.10.2

---

vip.sh

chore:add online doc link to CLI usage

---

install.sh
utils/install.sh
vip.sh

vcf/aip                                  | PASSED | 317590=completed output/vcf/aip/.nxf.log
vcf/chd7                                 | PASSED | 317591=completed output/vcf/chd7/.nxf.log
vcf/corner_cases                         | PASSED | 317592=completed output/vcf/corner_cases/.nxf.log
vcf/deb_register                         | PASSED | 317593=completed output/vcf/deb_register/.nxf.log
vcf/empty_input                          | PASSED | 317594=completed output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 317595=completed output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 317596=completed output/vcf/empty_output_filter/.nxf.log …

Bump nextflow to 24.10.3

---

config/nxf.config
utils/create_gnomad.sh
utils/create_mmi.sh
utils/install.sh
vip.sh

```
vcf/aip                                  | PASSED | 320507=completed test/output/vcf/aip/.nxf.log
vcf/chd7                                 | PASSED | 320508=completed test/output/vcf/chd7/.nxf.log
vcf/corner_cases                         | PASSED | 320509=completed test/output/vcf/corner_cases/.nxf.log
vcf/deb_register                         | PASSED | 320510=completed test/output/vcf/deb_register/.nxf.log
vcf/empty_input                          | PASSED | 320511=completed test/output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 320512=completed test/output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 320513=completed test/output/vcf/empty_output_filter/.nxf.log …
```

fix:Liftover broken or uses wrong container & small other fixes

---

config/nxf_vcf.config
install.sh

vcf/aip | PASSED | 324066=completed output/vcf/aip/.nxf.log
vcf/chd7 | PASSED | 324067=completed output/vcf/chd7/.nxf.log
vcf/corner_cases | PASSED | 324068=completed output/vcf/corner_cases/.nxf.log
vcf/deb_register | PASSED | 324069=completed output/vcf/deb_register/.nxf.log
vcf/empty_input | PASSED | 324070=completed output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples | PASSED | 324071=completed output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter | PASSED | 324072=completed output/vcf/empty_output_filter/.nxf.log
vcf/filter_samples | PASSED | 324073=completed output/vcf/filter_samples/.nxf.log
vcf/liftover | PASSED | 324074=completed output/vcf/liftover/.nxf.log …

Update report template (7.1.1)

---

modules/cram/coverage.nf

cram/complex                             |        | 336334=running   output/cram/complex/.nxf.log
cram/multiproject                        | PASSED | 336335=completed output/cram/multiproject/.nxf.log
cram/nanopore_duo                        | PASSED | 336336=completed output/cram/nanopore_duo/.nxf.log
cram/nanopore                            | PASSED | 336337=completed output/cram/nanopore/.nxf.log
cram/single                              | PASSED | 336338=completed output/cram/single/.nxf.log
cram/trio                                |        | 336339=running   output/cram/trio/.nxf.log

move coverage output to /coverage

---

config/nxf_vcf.config
install_data.sh

```
vcf/aip                                  | PASSED | 337939=completed test/output/vcf/aip/.nxf.log
vcf/chd7                                 | PASSED | 337940=completed test/output/vcf/chd7/.nxf.log
vcf/corner_cases                         | PASSED | 337941=completed test/output/vcf/corner_cases/.nxf.log
vcf/deb_register                         | PASSED | 337942=completed test/output/vcf/deb_register/.nxf.log
vcf/empty_input                          | PASSED | 337943=completed test/output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 337944=completed test/output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 337945=completed test/output/vcf/empty_output_filter/.nxf.log …
```

bump:inheritance_20241211.tsv to inheritance_20250131.tsv

---

install.sh
install_data.sh
test/suites/vcf/resources/str.vcf
test/suites/vcf/str.sh
utils/apptainer/def/annotsv-3.4.4.def

vcf/aip                                  | PASSED | 341073=completed output/vcf/aip/.nxf.log
vcf/chd7                                 | PASSED | 341074=completed output/vcf/chd7/.nxf.log
vcf/corner_cases                         | PASSED | 341075=completed output/vcf/corner_cases/.nxf.log
vcf/deb_register                         | PASSED | 341076=completed output/vcf/deb_register/.nxf.log
vcf/empty_input                          | PASSED | 341077=completed output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 341078=completed output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 341079=completed output/vcf/empty_output_filter/.nxf.log …

Move default VIP_URL_DATA + add exomizer jar for AnnotSV + fix STR test

---

modules/cram/templates/spectre_call.sh

cram/complex                             | PASSED | 340714=completed output/cram/complex/.nxf.log
cram/multiproject                        | PASSED | 340715=completed output/cram/multiproject/.nxf.log
cram/nanopore_duo                        | PASSED | 340716=completed output/cram/nanopore_duo/.nxf.log
cram/nanopore                            | PASSED | 340717=completed output/cram/nanopore/.nxf.log
cram/single                              | PASSED | 340718=completed output/cram/single/.nxf.log
cram/trio                                | PASSED | 340719=completed output/cram/trio/.nxf.log

Fix: Spectre VCF contains N ref nucleotides

---

config/nxf_call_str.config
install_data.sh
utils/apptainer/build.sh
utils/apptainer/def/straglr-1.4.5-vip-v2.def

cram/complex                             | PASSED | 345498=completed output/cram/complex/.nxf.log
cram/multiproject                        | PASSED | 345499=completed output/cram/multiproject/.nxf.log
cram/nanopore_duo                        | PASSED | 345500=completed output/cram/nanopore_duo/.nxf.log
cram/nanopore                            | PASSED | 345501=completed output/cram/nanopore/.nxf.log
cram/single                              | PASSED | 345502=completed output/cram/single/.nxf.log
cram/trio                                | PASSED | 345503=completed output/cram/trio/.nxf.log
done

Update straglr to 1.4.5-v2

---

install.sh

```
$ ./install.sh -v fix/install_sh
VIP fix/install_sh installation running...
VIP fix/install_sh installation completed, execute vip/fix_install_sh/vip.sh to get started
Slurm job scheduling system detected and will be used automatically
```
```
$ bash vip/fix_install_sh/install.sh --help
usage: bash install.sh.sh [-v <vip_version>] [-i <vip_install_dir>] [-d <data_dir>] [-u <url>] [-p]
-p, --prune     remove resources from previous VIP installs that are not required for this version.
-u, --url       base url to download VIP resources from
-d, --data_dir  directory where VIP resources should be installed
-i, --vip_dir   directory where the VIP software should be installed
-v, --version   VIP version to be installed
-h, --help
requirements:
apptainer    see https://apptainer.org/
bash …
```

fix: install.sh VIP_URL_DATA: unbound variable

---

resources/vcf_report_config.json

fix: don't show 'SV type' column for SNV in report

---

modules/vcf/templates/normalize.sh

vcf/aip                                  | PASSED | 377217=completed output/vcf/aip/.nxf.log
vcf/chd7                                 | PASSED | 377218=completed output/vcf/chd7/.nxf.log
vcf/corner_cases                         | PASSED | 377219=completed output/vcf/corner_cases/.nxf.log
vcf/deb_register                         | PASSED | 377220=completed output/vcf/deb_register/.nxf.log
vcf/empty_input                          | PASSED | 377221=completed output/vcf/empty_input/.nxf.log
vcf/empty_output_filter_samples          | PASSED | 377222=completed output/vcf/empty_output_filter_samples/.nxf.log
vcf/empty_output_filter                  | PASSED | 377223=completed output/vcf/empty_output_filter/.nxf.log …

Sort vcf after normalization

---

install.sh

```
>bash install.sh 
VIP v8.3.1 installation running...
VIP v8.3.1 installation completed, execute vip/v8.3.1/vip.sh to get started
Slurm job scheduling system detected and will be used automatically
>bash install.sh  --help
usage: bash install.sh [-v <vip_version>] [-i <vip_install_dir>] [-d <data_dir>] [-u <url>] [-p]
-p, --prune     remove resources from previous VIP installs that are not required for this version.
-u, --url       base url to download VIP resources from
-d, --data_dir  directory where VIP resources should be installed
-i, --vip_dir   directory where the VIP software should be installed
-v, --version   VIP version to be installed
-h, --help
requirements:
apptainer    see https://apptainer.org/ …
```

Fix: install.sh help prints success message

---

modules/fastq/fastp.nf

fix: Only publish fastp reports

---

modules/fastq/fastp.nf

Before submitting this PR, please make sure:
fastq/nanopore_adaptive_sampling         | PASSED | 406980=completed output/fastq/nanopore_adaptive_sampling/.nxf.log
```
[umcg-bcharbon@betabarrel intermediates]$ tree
.
├── fastp
│   ├── vip_fam0_HG002_report.html
│   └── vip_fam0_HG002_report.json
├── HG002_snv.g.vcf.gz
├── HG002_snv.g.vcf.gz.csi
├── HG002_snv.g.vcf.gz.stats
├── vip_annotations.vcf.gz
├── vip_annotations.vcf.gz.csi
├── vip_classifications.vcf.gz
├── vip_classifications.vcf.gz.csi
├── vip_fam0_HG002_cnv.vcf.gz
├── vip_fam0_HG002_cnv.vcf.gz.csi
├── vip_fam0_HG002_cnv.vcf.gz.stats
├── vip_fam0_HG002.cram
├── vip_fam0_HG002.cram.crai
├── vip_fam0_HG002.cram.stats
├── vip_fam0_HG002_str.tsv
├── vip_fam0_HG002_str.vcf.gz
├── vip_fam0_HG002_str.vcf.gz.csi
├── …
```

Only publish fastp reports
